# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "cloud-image/ubuntu-22.04"
  config.vm.hostname = "ubuntu-22.04"

  # SSH KEY
  config.ssh.insert_key = false
  # Enable ssh forward agent
  config.ssh.forward_agent = true
  

end
