# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# vagrant-precise32
#
# This is for updating the base precise32 box and repackage
#
box       = "precise32-base-20140221"
box_url   = "http://cdn.jlwestsr.com/vagrant/boxes/precise32-base-20140221.box"
hostname  = "vagrant-base-precise32"
domain    = "example.com" 
ip        = "192.168.0.40" # random ip address
ram       = "256" # adjust as needed

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box       = box
  #config.vm.box_url   = box_url
  config.vm.host_name = hostname + '.' + domain
  config.vm.network :private_network, ip: ip

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id, 
      "--name", hostname, 
      "--memory", ram
    ]
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :machine
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path    = "puppet/modules"
  end

end