# -*- mode: ruby -*-
# vi: set ft=ruby :

# Inline shell commands example
$script = <<SCRIPT
# Add shell commands here
uname -r
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/centos71"
  
  # Run the bootstrap.sh script to update VM
  config.vm.provision :shell, path: "bootstrap.sh"

  # Run inline shell script
  config.vm.provision :shell, inline: $script

  # Vagrant-Cachier - https://github.com/fgrehm/vagrant-cachier
  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
    config.cache.auto_detect = false
  end

  # Vagrant-VBGuest - https://github.com/dotless-de/vagrant-vbguest
  if Vagrant.has_plugin?("vagrant-vbguest")
    # we will try to autodetect this path. 
    # However, if we cannot or you have a special one you may pass it like:
    # config.vbguest.iso_path = "#{ENV['HOME']}/Downloads/VBoxGuestAdditions.iso"
    # or
    # config.vbguest.iso_path = "http://company.server/VirtualBox/%{version}/VBoxGuestAdditions.iso"

    # set auto_update to false, if you do NOT want to check the correct 
    # additions version when booting this machine
    config.vbguest.auto_update = false

    # do NOT download the iso file from a webserver
    # config.vbguest.no_remote = true    
  end

end