# -*- mode: ruby -*-
# vi: set ft=ruby :

# Commands required to setup working docker enviro, link
# containers, etc.
$setup = <<SCRIPT
# Stop and remove any existing containers
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

# Build containers from Dockerfiles
docker build -t base /vagrant/

SCRIPT

# Comands required to ensure correct docker containers
# are started when the vm is rebooted
$start = <<SCRIPT
docker start base
SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|

  # Setup resource requirements
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # need a private network for NFS shares to work
  #config.vm.network "private_network", ip: "192.168.50.4"

  # Rails Server Port Forwarding
  #config.vm.network "forwarded_port", guest: 3000, host: 3000

  # Ubuntu
  config.vm.box = "ubuntu/trusty64"

  # Run the bootstrap.sh script to update VM
  config.vm.provision :shell, path: "bootstrap.sh"

  # Install latest docker and provision
  config.vm.provision "docker" 

  # Must use NFS for this otherwise rails
  # performance will be awful
  #config.vm.synced_folder ".", "/app", type: "nfs"

  # Setup the containers when the VM is first created
  config.vm.provision :shell, inline: $setup

  # Make sure the correct containers are running
  # every time we start the VM
  config.vm.provision :shell, run: "always", inline: $start

end